from app.models.wiki.structure import Citation, Reference, Section, Article
from app.models.wiki.responses import (
    SourceArticleResponse,
    TranslateArticleResponse,
    StructuredArticleResponse,
    StructuredSectionResponse,
    StructuredCitationResponse,
    StructuredReferenceResponse,
    CitedArticle,
)
from app.models.wiki.analysis import (
    TableResponse,
    HeaderCount,
    InfoBoxResponse,
    CitationAnalysisResponse,
    FinalAnalysisResponse,
    MultiLanguageScoreResponse,
    AnalysisResultsResponse,
    TableInfo,
    InfoBoxAttribute,
)
from app.models.comparison.models import (
    CompareRequest,
    ComparisonResult,
    CompareResponse,
    SentenceDiff,
    SemanticCompareRequest,
    BaseCompareRequest,
    SectionCompareRequest,
    SectionCompareResponse,
    SectionDiff as SectionComparisonDiff,
    ParagraphDiff,
    ArticleComparisonResponse,
    MissingInfo,
    ExtraInfo,
)
from app.models.translation.models import ChunkedTranslateRequest
from app.models.api import (
    ModelSelectionResponse,
    ListResponse,
)
from app.models.extraction.models import (
    FactExtractionRequest,
    FactExtractionResponse,
)
from app.models.revision import (
    Revision,
    SectionDiff as RevisionSectionDiff,
    Flag,
    DiffResponse,
    LagReport,
    SectionChange,
    RevisionDiffResponse,
)

SectionDiff = SectionComparisonDiff

__all__ = [
    "Citation",
    "Reference",
    "Section",
    "Article",
    "SourceArticleResponse",
    "TranslateArticleResponse",
    "ArticleComparisonResponse",
    "MissingInfo",
    "ExtraInfo",
    "CompareRequest",
    "ComparisonResult",
    "CompareResponse",
    "SentenceDiff",
    "StructuredArticleResponse",
    "StructuredSectionResponse",
    "StructuredCitationResponse",
    "StructuredReferenceResponse",
    "CitedArticle",
    "TableResponse",
    "HeaderCount",
    "InfoBoxResponse",
    "CitationAnalysisResponse",
    "FinalAnalysisResponse",
    "MultiLanguageScoreResponse",
    "AnalysisResultsResponse",
    "TableInfo",
    "InfoBoxAttribute",
    "SemanticCompareRequest",
    "BaseCompareRequest",
    "ModelSelectionResponse",
    "ListResponse",
    "SectionCompareRequest",
    "SectionCompareResponse",
    "SectionComparisonDiff",
    "SectionDiff",
    "ParagraphDiff",
    "ChunkedTranslateRequest",
    "FactExtractionRequest",
    "FactExtractionResponse",
    "Revision",
    "RevisionSectionDiff",
    "Flag",
    "DiffResponse",
    "LagReport",
    "SectionChange",
    "RevisionDiffResponse",
]
